http:
  routers:
    router0:
      entryPoints:
        - web
        - websecure
      rule: Host(`blog.${HOST_DOMAIN}`)
      service: blog

  services:
    blog:
      loadBalancer:
        servers:
          - url: ${BLOG_SERVER_URL}

  serversTransports:
    pve:
      insecureSkipVerify: true

tcp:
  routers:
    minecraft-router:
      entryPoints:
        - minecraft
      rule: HostSNI(`*`)
      service: minecraft-server

  services:
    minecraft-server:
      loadBalancer:
        servers:
          - address: ${MINECRAFT_SERVER_URL}